config/routes.rb
NestJob::Application.routes.draw do
  captcha_route
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :accounts, controllers: { registrations: "accounts/registrations", sessions: "accounts/sessions", passwords: "accounts/passwords", mailer: "accounts/mailer" }, :sign_out_via=>[:delete, :get]
  devise_scope :account do
    post "/accounts/registrations/ajax_create" => "accounts/registrations#ajax_create"
    post "/accounts/sessions/ajax_create" => "accounts/sessions#ajax_create"
    post "/accounts/registrations/ajax_update_logo" => "accounts/registrations#ajax_update_logo"
    get "/accounts/registrations/edit_pwd" => "accounts/registrations#edit_pwd"
    patch "/accounts/registrations/update_pwd" => "accounts/registrations#update_pwd"
    
    get '/auth/:provider/callback' => 'accounts/sessions#auth_create'
  end
    
  get '/' => 'index#index'
  
  
  
  
  resources :help_center
  resources :index do
    collection do
      post :ajax_update_hope
      get :error_notice
      get :about
    end
  end
  
  
  
  
  
  resources :posts do
    collection do
      get :search
    end
  end
  
  resources :feedbacks
  
  
  

  
  resources :hr, controller: "hr/index", only: [] do
    collection do
      get :search
    end
  end
  namespace :hr do
    root to: "index#index"
    get ':id', to: 'index#show', constraints: {id: /\d+/}, shallow: true
    resources :posts do
      member do
        put :set_status
      end
    end
    resources :companies do
      collection do
        get :edit
        post :ajax_update_logo
      end
    end
    resources :company_members
    resources :company_scenes
    resources :applies do
      collection do
        post :receive
        post :accept
        post :reject
      end
    end
    resources :auditions do
      collection do
        post :pass
        post :fail
      end
    end
    resources :probations do
      collection do
        post :pass
        post :fail
      end
    end
  end
  
  
  
  
  namespace :worker do
    resources :resumes do
      collection do
        post :ajax_save
        post :update_price
        post :recharge
      end
    end
    resources :resume_experiences do
      collection do
        post :ajax_save
      end
    end
    resources :resume_objects do
      collection do
        post :ajax_save
      end
    end
    resources :resume_educations do
      collection do
        post :ajax_save
      end
    end
    resources :radars do
      collection do
        post :save
      end
    end
    resources :applies do
    end
    resources :resume_radars
    resources :invites
    resources :auditions do
    end
  end
  
  
  namespace :accounts do
    resources :favorites do
      collection do
        post :ajax_create
        post :ajax_destroy
      end
    end
  end
  
  
  

  
end

app/views/index/about.html.erb
<%content_for :head_include do%>
	<link rel="stylesheet" href="/鸟窝html/stylesheets/newtips.css" />
<%end%>

<div class="mainContainer">
	<div class="main">
		<!-- <div class="mm"> -->
			<h2 class="h2Title">关于鸟窝</h2>
			<ul class="newTips aboutNw">
				<li>
					<h3>简介</h3>
					<p>鸟窝，让高度匹配的靠谱求职者与靠谱招聘方自动找到对方</p>
				</li>
				<li>
					<h3>愿景</h3>
					<p>让HR不招人才，求职者不找工作</p>
				</li>
				<li>
					<h3>幸运的事</h3>
					<p>志同道合的朋友支持</p>
				</li>
				<li>
					<h3>请大家多吐槽</h3>
					<p>鸟窝是个小团队在做的产品，如果你发现问题</p>
					<p>请联系 QQ：939898101 或 邮件：939898101@qq.com</p>
					<p>我们会尽力一一回复。如果反馈的问题没有及时改进，那么我们肯定是在处理过程中。非常欢迎大家给我们吐槽各种问题。</p>
				</li>
			</ul>
	</div>
	<!-- </div> -->
  <%= render partial: "/layouts/right"%>
</div>

app/views/index/error_notice.html.erb
<%= flash[:error]%>

<%= link_to "返回", cookies[:goto]||"/"%>

app/views/index/index.html.erb
<div class="mainContainer">
	<div class="main">
		<div class="ml">
			<h2 class="regH2">推荐公司</h2>
			<ul class="brands loginTip" data-msgtip="请填写期望：职位与城市">
				<li><a href="#" class="baidu"><span>百度</span></a></li>
				<li><a href="#" class="baiduyun"><span>百度云</span></a></li>
				<li><a href="#" class="huaban"><span>花瓣</span></a></li>
				<li><a href="#" class="oneshop"><span>1号店</span></a></li>
				<li><a href="#" class="jd"><span>京东</span></a></li>
				<li><a href="#" class="sina"><span>新浪</span></a></li>
			</ul>
		</div>
		<div class="mm">
        <%= render partial: "/layouts/top_timeline"%>
        <%if @account_tags.blank? || @account_hope_area.blank?%>
        <!--图片轮播start-->
        <%= stylesheet_link_tag    '/鸟窝html/javascripts/flash/style/screen.css', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag '/鸟窝html/javascripts/flash/js/modernizr.min.js', 'data-turbolinks-track' => true %>
        <div id="page">
        	<div id="viewport-shadow" class="trans">
        		<a href="#" id="prev" title="go to the next slide" class="trans"></a>
        		<a href="#" id="next" title="go to the next slide" class="trans"></a>
        		<div id="viewport">
        			<div id="box">
        				<figure class="slide"><a href="#" target="_blank"><img src="/鸟窝html/javascripts/flash/images/focus_1.jpg"></a></figure>
        				<figure class="slide"><a href="#" target="_blank"><img src="/鸟窝html/javascripts/flash/images/focus_2.jpg"></a></figure>
        				<figure class="slide"><a href="#" target="_blank"><img src="/鸟窝html/javascripts/flash/images/focus_3.jpg"></a></figure>
        				<figure class="slide"><img src="/鸟窝html/javascripts/flash/images/focus_4.jpg"></figure>
        				<figure class="slide"><img src="/鸟窝html/javascripts/flash/images/focus_5.jpg"></figure>
        			</div>
        		</div>
        		<div id="time-indicator"></div>
        	</div>
        	<div class="slider-controls">
        		<ul id="controls">
        			<li><a class="goto-slide current" href="#" data-slideindex="0"></a></li>
        			<li><a class="goto-slide" href="#" data-slideindex="1"></a></li>
        			<li><a class="goto-slide" href="#" data-slideindex="2"></a></li>
        			<li><a class="goto-slide" href="#" data-slideindex="3"></a></li>
        			<li><a class="goto-slide" href="#" data-slideindex="4"></a></li>
        		</ul>
        	</div>
        </div>
        <script type="text/javascript" src="/鸟窝html/javascripts/flash/js/box-slider-all.jquery.min.js"></script>
       <script type="text/javascript">
       $(function(){

       	var $box = $('#box'), $indicators = $('.goto-slide'), $timeIndicator = $('#time-indicator'), slideInterval = 5000;

       	var switchIndicator = function ($c, $n, currIndex, nextIndex) {
       		$timeIndicator.stop().css('width', 0);
       		$indicators.removeClass('current').eq(nextIndex).addClass('current');
       	};

       	var startTimeIndicator = function () {
       		$timeIndicator.animate({width: '716px'}, slideInterval);
       	};

       	// initialize the plugin with the desired settings
       	$box.boxSlider({
       		speed: 1000,
       		autoScroll: true,
       		timeout: slideInterval,
       		next: '#next',
       		prev: '#prev',
       		pause: '#pause',
       		effect: 'scrollVert3d', /*scrollVert3d and scrollHorz3d*/
       		blindCount: 15,
       		onbefore: switchIndicator,
       		onafter: startTimeIndicator
       	});

       	startTimeIndicator();

       	// pagination isn't built in simply because it's easy to
       	// roll your own with the plugin API methods
       	$('#controls').on('click', '.goto-slide', function (ev){
       		$box.boxSlider('showSlide', $(this).data('slideindex'));
       		ev.preventDefault();
       	});

       });

       </script>
        <!--图片轮播 end-->
        <!--h2 class="indexH2">找高薪工作、赚签约金？填写期望职位，才能进行下一步哦！</h2-->
                <div class="postForm" style='display:none'>
                    <div class="hopePost">
                        <div class="frm">
                            <span>期望职位：</span>
                            <div class="posts" id="addHopePanel">
                            </div>

                            <div class="postInput">
                                <input type="text" id="addHopeContent"><a href="javascript:void(0)" id="addHope" class="addPost"><em>&nbsp;</em></a>
                            </div>
                        </div>
                        <div class="">
                            <span>期望城市：</span>
                            <div class="postInput">
                                <select id="cityHopes" data-placeholder="选择城市" style="width:100px;height:40px"><select>
                            </div>
                        </div>
                        <br>
                        <a href="javascript:void(0)" id="saveHopes" class="saveBtn">保存印记</a>
                    </div>
                </div>
                <div style="color: #199594;"><span style='cursor:pointer'>热门职位</span> | <span style='cursor:pointer'>高薪职位</span>| <span style='cursor:pointer'>急招职位</span></div>
                <!--xxl start-->
                <ul class="employment">
                  			<li class="selectcurrent">
                  				<div class="employInfo">
                  					<div class="userImg"><a href="#"><img alt="Album cover" src="/uploads/accounts/logos/79/thumb/album_cover.jpg?1408611932"></a></div>
                  					<div class="employDetail">
                  						<p><span class="b">王雅然   （9238**@qq.com）</span><span>发布了  <b>前端</b>&nbsp;2.4251974</span></p>
                  						<p><span class="b">地点：北京市朝阳区</span><span class="b">  •  公司：遇上科技</span><span class="b">  •  薪资：20k ~ 30k</span></p>
                  						<dl>
                  						 	<dt>职位要求：</dt>
                                2、与后台工程师配合，展示数据；3、特殊js交互效果的实现，Ajax代码实现；4、<b>前端</b>代码优化；5、配合其他部门完成专题页面或EDM等制作。&nbsp;
                  						 </dl>
                  					</div>
                  				</div>

                  				<div class="employBtns">
                              <a href="/accounts/sign_in" jobid="132" class="btnR initiateInterviewBtn">发起面试</a>
                            <a href="/posts/132" class="btnR">查    看</a>
                            <!--a jobid="132"  onclick="addCollect(this)" href="/accounts/sign_in" class="btnR">收    藏</a-->
                  				</div>
                  			</li>
                  			<li class="selectcurrent">
                  				<div class="employInfo">
                  					<div class="userImg"><a href="#"><img alt="Album cover" src="/uploads/accounts/logos/79/thumb/album_cover.jpg?1408611932"></a></div>
                  					<div class="employDetail">
                  						<p><span class="b">王雅然   （9238**@qq.com）</span><span>发布了  <b>前端</b>&nbsp;2.4251974</span></p>
                  						<p><span class="b">地点：北京</span><span class="b">  •  公司：遇上科技</span><span class="b">  •  薪资：10k ~ 20k</span></p>
                  						<dl>
                  						 	<dt>职位要求：</dt>
                                2、与后台工程师配合，展示数据；3、特殊js交互效果的实现，Ajax代码实现；4、<b>前端</b>代码优化；5、配合其他部门完成专题页面或EDM等制作。&nbsp;
                  						 </dl>
                  					</div>
                  				</div>

                  				<div class="employBtns">
                              <a href="/accounts/sign_in" jobid="133" class="btnR initiateInterviewBtn">发起面试</a>
                            <a href="/posts/133" class="btnR">查    看</a>
                            <!--a jobid="133"  onclick="addCollect(this)" href="/accounts/sign_in" class="btnR">收    藏</a-->
                  				</div>
                  			</li>
                  			<li class="selectcurrent">
                  				<div class="employInfo">
                  					<div class="userImg"><a href="#"><img alt="Album cover" src="/uploads/accounts/logos/52/thumb/album_cover.jpg?1406255931"></a></div>
                  					<div class="employDetail">
                  						<p><span class="b">云天使基金   （**@cloudangelfunds.com）</span><span>发布了  <b>前端</b>&nbsp;2.4251974</span></p>
                  						<p><span class="b">地点：建外SOHO14号楼506</span><span class="b">  •  公司：北京科技</span><span class="b">  •  薪资：15k ~ 30k</span></p>
                  						<dl>
                  						 	<dt>职位要求：</dt>
                                职位描述技术大牛们，<b>前端</b>攻城狮赶紧看过来！
                  						 </dl>
                  					</div>
                  				</div>

                  				<div class="employBtns">
                              <a href="/accounts/sign_in" jobid="127" class="btnR initiateInterviewBtn">发起面试</a>
                            <a href="/posts/127" class="btnR">查    看</a>
                            <!--a jobid="127"  onclick="addCollect(this)" href="/accounts/sign_in" class="btnR">收    藏</a-->
                  				</div>
                  			</li>
                  			<li class="selectcurrent">
                  				<div class="employInfo">
                  					<div class="userImg"><a href="#"><img alt="Album cover" src="/uploads/accounts/logos/10/thumb/album_cover.jpg?1402568837"></a></div>
                  					<div class="employDetail">
                  						<p><span class="b">死神   （3495**@qq.com）</span><span>发布了  Web<b>前端</b>开发工程师&nbsp;1.0610238</span></p>
                  						<p><span class="b">地点：北京海淀区知春路锦秋国际大厦</span><span class="b">  •  公司：一点科技</span><span class="b">  •  薪资：20k ~ 30k</span></p>
                  						<dl>
                  						 	<dt>职位要求：</dt>
                                招聘岗位： Web<b>前端</b>开发工程师工作职责：— 负责一点资讯Web/WebApp等<b>前端</b>工作任职条件：— 熟悉WEB<b>前端</b>技术，对符合WEB标准的网站重构有丰富经验，有成功作品— 理解并掌握Javascript语言核心技术DOM、BOM、Ajax、JSON等，对Javascript框架应用（如jQuery/bootstrap等）有一定的经验—	熟悉NodeJS, coffeescript优先—	对CSS/Javascript性能优化、解决多浏览器兼容性问题有一定的经验—	对用户体验、交互操作...
                  						 </dl>
                  					</div>
                  				</div>

                  				<div class="employBtns">
                              <a href="/accounts/sign_in" jobid="128" class="btnR initiateInterviewBtn">发起面试</a>
                            <a href="/posts/128" class="btnR">查    看</a>
                            <!--a jobid="128"  onclick="addCollect(this)" href="/accounts/sign_in" class="btnR">收    藏</a-->
                  				</div>
                  			</li>
                  			<li class="selectcurrent">
                  				<div class="employInfo">
                  					<div class="userImg"><a href="#"><img alt="Album cover" src="/uploads/accounts/logos/10/thumb/album_cover.jpg?1402568837"></a></div>
                  					<div class="employDetail">
                  						<p><span class="b">死神   （2**234@qq.com）</span><span>发布了  产品运营&nbsp;0.267949</span></p>
                  						<p><span class="b">地点：北京市朝阳区朝外SOHO</span><span class="b">  •  公司：公司一</span><span class="b">  •  薪资：15k ~ 25k</span></p>
                  						<dl>
                  						 	<dt>职位要求：</dt>
                                开发维护<b>前端</b>团队自有框架3.
                  						 </dl>
                  					</div>
                  				</div>

                  				<div class="employBtns">
                              <a href="/accounts/sign_in" jobid="119" class="btnR initiateInterviewBtn">发起面试</a>
                            <a href="/posts/119" class="btnR">查    看</a>
                            <!--a jobid="119"  onclick="addCollect(this)" href="/accounts/sign_in" class="btnR">收    藏</a-->
                  				</div>
                  			</li>
                  		</ul>
                  		<!--xxl end-->
                <%else%>
                  <%resume_is_complete = current_account && current_account.current_account_resume.complete?%>
                  <%if @hot_posts.present?%>
                    <p class="nohopeJob">您期望的职位让小伙们惊呆了( ⊙ o ⊙ )啊！居然没有，我们会尽快补全，尝试一下其它职位吧！</p>
                  <%end%>
                		<ul class="employment">
                			<%(@posts || @hot_posts).each do |post|%>
                			<li class="selectcurrent">
                				<div class="employInfo">
                					<div class="userImg"><%= link_to image_tag(post.account.logo(:thumb)), "#"%></div>
                					<div class="employDetail">
                						<p><span class="b"><%= post.account.nick_name%>   （<%= post.protect_email%>）</span><span>发布了  <%= post.title%></span></p>
                						<p><span class="b">地点：<%= post.address%></span><span class="b">公司：<%= post.company.name%></span><span class="b">薪资：<%= "#{post.price_min.to_i}k ~ #{post.price_max.to_i}k"%></span></p>
                						<dl>
                						 	<dt>职位要求：</dt>
                						 	<%= raw truncate_u(post.sanitize_content.to_s, 200) %>
                						 </dl>
                					</div>
                				</div>

                				<div class="employBtns">
                					<a href="javascript:void(0)" jobid="<%= post.id%>" class="btnR initiateInterviewBtn" resume_complete="<%= resume_is_complete%>">发起面试</a><a href="<%= post_path(post)%>" class="btnR">查    看</a><!--a jobid="<%= post.id%>"  onclick="addCollect(this)" href="javascript:void(0)" class="btnR">收    藏</a-->
                				</div>
                			</li>
                      <%end%>
                		</ul>
                    <%= paginate (@posts || @hot_posts), window: 6%>
                <%end%>
		</div>
	</div>
	<%= render partial: "/layouts/right"%>
</div>