config/routes.rb
NestJob::Application.routes.draw do
  captcha_route
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :accounts, controllers: { registrations: "accounts/registrations", sessions: "accounts/sessions", passwords: "accounts/passwords", mailer: "accounts/mailer" }, :sign_out_via=>[:delete, :get]
  devise_scope :account do
    post "/accounts/registrations/ajax_create" => "accounts/registrations#ajax_create"
    post "/accounts/sessions/ajax_create" => "accounts/sessions#ajax_create"
    post "/accounts/registrations/ajax_update_logo" => "accounts/registrations#ajax_update_logo"
    get "/accounts/registrations/edit_pwd" => "accounts/registrations#edit_pwd"
    patch "/accounts/registrations/update_pwd" => "accounts/registrations#update_pwd"
    
    get '/auth/:provider/callback' => 'accounts/sessions#auth_create'
  end
    
  get '/' => 'index#index'
  
  
  
  
  resources :help_center
  resources :index do
    collection do
      post :ajax_update_hope
      get :error_notice
      get :about
    end
  end
  
  
  
  
  
  resources :posts do
    collection do
      get :search
    end
  end
  
  resources :feedbacks
  
  
  

  
  resources :hr, controller: "hr/index", only: [] do
    collection do
      get :search
    end
  end
  namespace :hr do
    root to: "index#index"
    get ':id', to: 'index#show', constraints: {id: /\d+/}, shallow: true
    resources :posts do
      member do
        put :set_status
      end
    end
    resources :companies do
      collection do
        get :edit
        post :ajax_update_logo
      end
    end
    resources :company_members
    resources :company_scenes
    resources :applies do
      collection do
        post :receive
        post :accept
        post :reject
      end
    end
    resources :auditions do
      collection do
        post :pass
        post :fail
      end
    end
    resources :probations do
      collection do
        post :pass
        post :fail
      end
    end
  end
  
  
  
  
  namespace :worker do
    resources :resumes do
      collection do
        post :ajax_save
        post :update_price
        post :recharge
      end
    end
    resources :resume_experiences do
      collection do
        post :ajax_save
      end
    end
    resources :resume_objects do
      collection do
        post :ajax_save
      end
    end
    resources :resume_educations do
      collection do
        post :ajax_save
      end
    end
    resources :radars do
      collection do
        post :save
      end
    end
    resources :applies do
    end
    resources :resume_radars
    resources :invites
    resources :auditions do
    end
  end
  
  
  namespace :accounts do
    resources :favorites do
      collection do
        post :ajax_create
        post :ajax_destroy
      end
    end
  end
  
  
  

  
end

app/controllers/accounts/account_post_applies_controller.rb
class Accounts::AccountPostAppliesController < ApplicationController
  before_action :authenticate_account!
  
  def ajax_create
    result = {status: "ok"}
    begin
      post_id = params[:post_id]
      price = params[:price].to_f
      message = params[:message]

      resource = AccountPostApply.new(post_id: post_id, price: price, message: message)
      unless resource.save
        raise AjaxException.new(resource.errors.messages.inject({}){|hash, item| hash[item[0]] = item[1]*','; hash})
      end
    rescue Exception => ex
      result = {status: "error", content: ex.message}
      logger.error "accounts_create error log================================================"
      logger.error ex.message
      logger.error ex.backtrace
    end
    render json: result.to_json 
  end
end

app/controllers/accounts/application_controller.rb
class ApplicationController < ActionController::Base
  # reset captcha code after each request for security
  after_filter :reset_last_captcha_code!

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  
  #protected####################################################
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit({ roles: [] }, :email, :password, :remember_me, :authentication_token) }
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :authentication_token) }
  end
  
  def get_cookie_id
    return cookies.permanent[:cookie_id] ||= SecureRandom.uuid
  end
end

app/controllers/accounts/companies_controller.rb
class Accounts::CompaniesController < ApplicationController
  before_action :authenticate_account!
  
  def new
    if current_account.company.present?
      flash[:error] = "已经完善过公司信息"
      cookies[:goto] ||= "/"
      redirect_to error_notice_index_index_path and return
    end
  end
  
  def create
    company = current_account.build_company(company_create_params)
    unless company.save
      flash[:error] = company.errors.messages.inject({}){|hash, item| hash[item[0]] = item[1]*','; hash}
      redirect_to :back and return
    end
    #保存所在公司
    current_account.save
    
    redirect_to cookies[:goto]||accounts_profile_index_path
  end
  
  private  
  def company_create_params  
    params.require(:company).permit()  
  end  
end

app/controllers/accounts/favorites_controller.rb
class Accounts::FavoritesController < ApplicationController
  before_action :authenticate_account!
  
  def index
    @favorites = current_account.favorites.page(params[:page]).per(5)
  end
  
  def ajax_create
    result = {status: "ok"}
    begin
      raise "收藏类型错误" unless ["post", "account_resume"].include?(params[:item_type])
      item = params[:item_type].classify.constantize.find params[:id] rescue raise "内容不存在"
  
      current_account.favorites.create(item_type: item.class.to_s, item_id: item.id) unless current_account.favorites.by_item(item).first
    rescue Exception => ex
      result = {status: "error", content: ex.message}
      logger.error "accounts_create error log================================================"
      logger.error ex.message
      logger.error ex.backtrace
    end
    render json: result.to_json
  end
  
  # ajax取消收藏
  #
  # 作者: 赵晓龙
  # 最后更新时间: 2014-06-18
  #
  # ==== 访问地址
  # /accounts/favorites/ajax_destroy
  # ==== 请求类型
  # post
  # ==== 参数
  # item_type: 条目类型
  # id: 条目id
  # ==== 返回类型
  # {status: "ok"}
  def ajax_destroy
    result = {status: "ok"}
    begin
      if params[:item_type].present?
        item = params[:item_type].classify.constantize.new(id: params[:id])
        current_account.favorites.by_item(item).first.destroy rescue raise "内容不存在"
      else
        current_account.favorites.destroy params[:id] rescue raise "内容不存在"
      end
    rescue Exception => ex
      result = {status: "error", content: ex.message}
      logger.error "accounts_create error log================================================"
      logger.error ex.message
      logger.error ex.backtrace
    end
    render json: result.to_json
  end
end

app/controllers/accounts/passwords_controller.rb
class Accounts::PasswordsController < Devise::PasswordsController  
  layout false
  include DiversityResult
  
  def create
    begin
      @email = params[:email]
      raise "用户不存在" unless resource = Account.by_email(@email).first
      resource.send_reset_password_instructions
    rescue Exception => ex
      flash[:error] = ex.message
      logger.error "action error log================================================"
      logger.error ex.message
      logger.error ex.backtrace
    end
    dr_render do
      if flash[:error].present?
        redirect_to :back
      else
        render :success
      end
    end
  end
  
  def edit
    begin
      @email = params[:email]
      raise "用户不存在" unless resource = Account.by_email(@email).first
      raise I18n.t("errors.messages.expired") unless resource.reset_password_period_valid?
      super
    rescue Exception => ex
      flash[:error] = ex.message
      logger.error "action error log================================================"
      logger.error ex.message
      logger.error ex.backtrace
      redirect_to new_account_password_path and return
    end
  end
  
  def update
    super do
      if resource.errors.messages[:reset_password_token].present?
        flash[:error] = resource.errors.messages[:reset_password_token].join(",")
        redirect_to new_account_password_path and return
      end
    end
  end
end

app/controllers/accounts/posts_controller.rb
class Accounts::PostsController < ApplicationController
  before_action :authenticate_account!
  
  def index
    @posts = current_account.posts.ct_desc.page(params[:id]).per(8)
  end
  
	def new
    if current_account.company.blank?
      cookies[:goto] = request.original_url
      redirect_to new_accounts_company_path and return
    end
    
		@post = Post.new
	end
  
  def create
    post = Post.new(post_create_params)
    post.account_id = current_account.id
    post.content = params[:editorValue]
    post.tag_list.add params[:addhopecontenthidden].split(",")
    post.sanitize_content = Nokogiri.parse(post.content).text if post.content.present? #去掉html标记的内容取200个字
    #TODO: 公司ID
    post.company_id = Company.last.id
    post.save
    flash[:notice] = "保存完成"
    redirect_to accounts_post_path(post)
  end
  
  def show
    @post = Post.find(params[:id])
    @company = @post.company
  end
  
  def ajax_get_tags
    Elasticsearch::Client.new.indices.analyze(index: "index", text: params[:title])
  end
  
  private  
  def post_create_params  
    params.require(:post).permit(:title, :area, :price_min, :price_max, :address, :email, :department, :content)  
  end  
end

app/controllers/accounts/profile_controller.rb
class Accounts::ProfileController < ApplicationController
  before_action :authenticate_account!
  
  def edit
    
  end
  
  
end

app/controllers/accounts/registrations_controller.rb
class Accounts::RegistrationsController < Devise::RegistrationsController
  skip_after_filter :reset_last_captcha_code!, :only=>[:ajax_create]
  
  def new
    super
  end
  
  def ajax_create
    result = {status: "ok"}
    begin
      unless captcha_valid? params[:captcha]
        #更新验证码
        reset_last_captcha_code!
        #验证码错误
        raise AjaxException.new({captcha: "验证码错误"})
      end
      resource = Account.new(
        email: params[:account][:email],
        password: params[:account][:password],
        account_type: params[:user_type]
      )
      unless resource.save
        #创建失败
        raise AjaxException.new(resource.errors.messages.inject({}){|hash, item| hash[item[0]] = item[1]*','; hash})
      end
      
      #从cookie取出首页的期望城市和职位标签存入简历
      current_account_resume = resource.current_account_resume
      current_account_resume.hope_area = cookies[:account_hope_area] if cookies[:account_hope_area].present?
      current_account_resume.tag_list.add(cookies[:account_tag_list].split(",")) if cookies[:account_tag_list].present?
      current_account_resume.save
      
      #判断是否是微博绑定用户，如果是则绑定微博账号
      if params[:provider].present? && params[:uid].present?
        if auth = Authorization.by_auth(params[:provider], params[:uid]).first
          auth.bind_account(resource)
        end
      end
      
      #登陆
      sign_in(:account, resource)
      register_step2_path = resource.account_type == Account::ACCOUNT_TYPE_HR ? new_hr_company_path : edit_account_registration_path
      #cookies[:goto]||after_sign_in_path_for(resource)
      result = {status: "ok", content: (register_step2_path)}
    rescue Exception => ex
      result = {status: "error", content: ex.message}
      logger.error "accounts_create error log================================================"
      logger.error ex.message
      logger.error ex.backtrace
    end
    render json: result.to_json
  end
  
  def update
    begin
      if current_account.update_attributes(account_update_params)
        flash[:success] = "保存成功"
      else
        flash[:error] = current_account.errors
      end
    rescue Exception => ex
      flash[:error] = ex.message
    end
    
    redirect_to :back
  end
  
  def ajax_update_logo
    result = {status: "ok"}
    begin
      current_account.logo = params[:file]
      unless current_account.save
        raise AjaxException.new(current_account.errors.messages.inject({}){|hash, item| hash[item[0]] = item[1]*','; hash})
      end
      result[:content] = current_account.logo(:thumb)
    rescue Exception => ex
      result = {status: "error", content: ex.message}
      logger.error "ajax_update_logo error log================================================"
      logger.error ex.message
      logger.error ex.backtrace
    end
    render text: result.to_json
  end
  
  def edit_pwd
    
  end
  
  def update_pwd
    begin
      raise "现用密码不正确" unless current_account.valid_password?(params[:account][:current_password])
      current_account.password = params[:account][:password]
      current_account.password_confirmation = params[:account][:password_confirmation]
      raise current_account.errors.messages.values * "," unless current_account.save
      flash[:success] = "修改成功"
    rescue Exception => ex
      flash[:error] = ex.message
      logger.error "ajax_update_logo error log================================================"
      logger.error ex.message
      logger.error ex.backtrace
    end
    redirect_to :back
  end
  
  private  
  def account_update_params  
    params.require(:account).permit(:nick_name, :company_email, :description, :industry_id)  
  end 
end

app/controllers/accounts/resumes_controller.rb
class Accounts::ResumesController < ApplicationController
  before_action :authenticate_account!
  
  def index
    @account_resume = AccountResume.find_or_create_by(account_id: current_account.id)
    @experiences = @account_resume.account_resume_experiences
    @objects = @account_resume.account_resume_objects
    @educations = @account_resume.account_resume_educations
  end
  
  def ajax_save
    result = {status: "ok"}
    begin
      account_resume = current_account.current_account_resume
      unless account_resume.update_attributes(resume_params)
        raise AjaxException.new(account_resume.errors.messages.inject({}){|hash, item| hash[item[0]] = item[1]*','; hash})
      end
      account_resume.tag_list = account_resume.tags.split(",")
    rescue Exception => ex
      result = {status: "error", content: ex.message}
      logger.error "accounts_create error log================================================"
      logger.error ex.message
      logger.error ex.backtrace
    end
    render result.to_json
  end
  
  private  
  def resume_params  
    params.require(:account_resume).permit(:name, :tel, :email, :birthday, :gender, :education, :price, :marital_status, :address, :hope_salary, :hope_area, :tags)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
	  @posts = Post.ct_desc.page(params[:page]).per(5)
	end
  
  def show
    @post = Post.find(params[:id])
    @post.update_attribute(:look_num, @post.look_num + 1)
    @company = @post.company
  end
  
  def search
    area = params[:area]
    k = params[:k]
    filter = {}
    @posts  = nil
    
    
    if k.present?
      #记录热搜词
      k.split(' ').each do|key|
        if current_account.present?
          search_tag = HotSearchTag.find_or_create_by(account_id: current_account.id, name: key)
          search_tag.industry_id = current_account.industry_id
        else
          search_tag = HotSearchTag.find_or_create_by(cookie_id: get_cookie_id, name: key)
        end
        search_tag.search_count = search_tag.search_count.to_i + 1
        search_tag.save
      end
      
      filter = {
        "bool" => {"must" => {"term" => { "area" => area }}}
      } if area.present?
      
      @time = Benchmark.realtime do
        @posts = Post.__elasticsearch__.search "query" => {
          "multi_match" => {
            "query" => k,
            "fields" => [ "title", "address", "sanitize_content" ]
          }
        },
        "filter" => filter,
        "sort" => [],
        "facets" => {},
        highlight: { 
          fields: { 
            title: {"pre_tags" => ["<b>"], "post_tags" => ["</b>"]}, 
            sanitize_content: {"pre_tags" => ["<b>"], "post_tags" => ["</b>"]}, 
            address: {"pre_tags" => ["<b>"], "post_tags" => ["</b>"]} 
          } 
        }
      end
      @posts = @posts.page(params[:page]).per(5)
      @records = @posts.records.includes(:account)
      @posts = @posts.results
    else
      redirect_to posts_path and return
    end
  end

end

app/helpers/accounts/account_post_applies_helper.rb
module Accounts::AccountPostAppliesHelper
end

app/helpers/accounts/companies_helper.rb
module Accounts::CompaniesHelper
end

app/helpers/accounts/favorites_helper.rb
module Accounts::FavoritesHelper
end

app/helpers/accounts/posts_helper.rb
module Accounts::PostsHelper
end

app/helpers/accounts/profile_helper.rb
module Accounts::ProfileHelper
end

app/helpers/accounts/resume_educations_helper.rb
module Accounts::ResumeEducationsHelper
end

app/views/accounts/posts/new.html.erb
<%= content_for :head_include do%>
	<link rel="stylesheet" href="/鸟窝html/stylesheets/ui_common.css" />
	<link rel="stylesheet" href="/鸟窝html/stylesheets/release_job.css" />
  <script type="text/javascript" charset="utf-8" src="/鸟窝html/javascripts/ueditor1_4_3-src/ueditor.config.js"></script>
  <script type="text/javascript" charset="utf-8" src="/鸟窝html/javascripts/ueditor1_4_3-src/_examples/editor_api.js"></script>
<%end%>
<div class="mainContainer">
	<div class="main">
		<!-- <div class="ml">
		</div> -->
		<!-- <div class="mm"> -->
			<h2 class="h2Title">发布职位 | <a href="#">今天发布了2个职位</a></h2>
			<div class="form">
				<%= form_for @post, url: accounts_posts_path, method: :post do |f|%>
        <%if flash[:error]%>
        <span style="color: red">错误信息:<%= flash[:error]%></span>
        <%end%>
        <%if flash[:notice]%>
        <span style="color: green">提示信息:<%= flash[:notice]%></span>
        <%end%>
				<div class="frm">
					<span>职位名称</span>
					<%= f.text_field :title,id: "jobName", class: "verification","data-noHide" => "1","error-id" => "errorjobName","data-type" => "notnull"%>
					<span class="error" id="errorjobName">*请填写职位名称</span>
				</div>
				<div class="frm">
					<span class="">工作城市</span>
					<%= f.text_field :area,id: "jobCity", class: "verification","data-noHide" => "1","error-id" => "errorjobCity","data-type" => "notnull"%>
					<span class="error" id="errorjobCity">*请填写城市名称</span>
				</div>
				<div class="frm">
					<span class="">薪资范围</span>
					<%= f.text_field :price_min, class: "small verification",id: "jobMoneyOne","data-noHide" => "1","error-id" => "errorjobMoney","data-type" => "money"%>
          <span class="smallR">k ~</span>
					<%= f.text_field :price_max, class: "small verification",id: "jobMoneyTwo","data-noHide" => "1","error-id" => "errorjobMoney","data-type" => "money"%>
          <span class="smallR" style="margin-right:80px;">k</span>
					<span class="error" id="errorjobMoney">*请填写薪资范围，输入 0~500 的整数</span>
				</div>
				<div class="frm">
					<span class="">详细工作地点</span>
					<%= f.text_field :address,id: "jobAddress", class: "verification","data-noHide" => "1","error-id" => "errorjobAddress","data-type" => "notnull"%>
					<span class="error" id="errorjobAddress">*请填写详细工作地点</span>
				</div>
				<div class="frm">
					<span class="">接收简历邮箱</span>
					<%= f.text_field :email,id: "jobEmail", class: "verification","data-noHide" => "1","error-id" => "errorjobEmail","data-type" => "notnull"%>
					<span class="error" id="errorjobEmail">*请填写接收简历的邮箱</span>
				</div>
				<div class="frm">
					<span class="">所在部门</span>
					<%= f.text_field :department,id: "jobDepartment", class: "verification","data-noHide" => "1","error-id" => "errorjobDepartment","data-type" => "notnull"%>
					<span class="error" id="errorjobDepartment">*请填写职位所在部门</span>
				</div>
				<div class="frm">
					<span class="">职位详情</span>
          <script  type="text/plain" id="myEditor">
              <p><%= @post.content%></p>
          </script>
          <script type="text/javascript">
              var myEditor = UE.getEditor('myEditor',{
                  //这里可以选择自己需要的工具按钮名称,此处仅选择如下五个
                  toolbars:[[ 'Undo', 'Redo','Bold','test', 'insertimage', 'paragraph','fontsize','autotypeset']],
                  //focus时自动清空初始化时的内容
                  autoClearinitialContent:true,
                  //关闭字数统计
                  wordCount:false,
                  scaleEnabled:true,
                  //关闭elementPath
                  elementPathEnabled:false,
                  //默认的编辑区域高度
                  initialFrameHeight:200,
                  initialFrameWidth:335
                  //更多其他参数，请参考ueditor.config.js中的配置项
              })
          </script>
					<span class="error jobMore">*请填写职位详情</span>
				</div>
				<div class="frm">
					<span class="">职位关键词</span>
					<div class="posts" id="addHopePanel">

					</div>
					 <div style="clear:both"></div>
					<div class="postInput">
          <input type="text" id="addHopeContent" />
					<a href="javascript:void(0)" data-max="1" id="addHope" class="addPost"><em>&nbsp;</em></a>
					</div>
					<span>请填写职位关键词，方便应聘方搜索您的职位</span>
				</div>
			</div>
			<div class="jobBtns">
				<!-- <a href="#" class="btnR">发起面试</a><a href="#" class="btnR">收    藏</a> -->
				<input type="hidden" value="" name="addhopecontenthidden" id="addHopeContenthidden">
                <a class="btn" href="javascript:void(0)" id="positionIssue">发布职位</a>
			</div>
			<%end%>
		</div>
	
	<%= render partial: "/layouts/right"%>
</div>