config/routes.rb
NestJob::Application.routes.draw do
  captcha_route
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :accounts, controllers: { registrations: "accounts/registrations", sessions: "accounts/sessions", passwords: "accounts/passwords", mailer: "accounts/mailer" }, :sign_out_via=>[:delete, :get]
  devise_scope :account do
    post "/accounts/registrations/ajax_create" => "accounts/registrations#ajax_create"
    post "/accounts/sessions/ajax_create" => "accounts/sessions#ajax_create"
    post "/accounts/registrations/ajax_update_logo" => "accounts/registrations#ajax_update_logo"
    get "/accounts/registrations/edit_pwd" => "accounts/registrations#edit_pwd"
    patch "/accounts/registrations/update_pwd" => "accounts/registrations#update_pwd"
    
    get '/auth/:provider/callback' => 'accounts/sessions#auth_create'
  end
    
  get '/' => 'index#index'
  
  
  
  
  resources :help_center
  resources :index do
    collection do
      post :ajax_update_hope
      get :error_notice
      get :about
    end
  end
  
  
  
  
  
  resources :posts do
    collection do
      get :search
    end
  end
  
  resources :feedbacks
  
  
  

  
  resources :hr, controller: "hr/index", only: [] do
    collection do
      get :search
    end
  end
  namespace :hr do
    root to: "index#index"
    get ':id', to: 'index#show', constraints: {id: /\d+/}, shallow: true
    resources :posts do
      member do
        put :set_status
      end
    end
    resources :companies do
      collection do
        get :edit
        post :ajax_update_logo
      end
    end
    resources :company_members
    resources :company_scenes
    resources :applies do
      collection do
        post :receive
        post :accept
        post :reject
      end
    end
    resources :auditions do
      collection do
        post :pass
        post :fail
      end
    end
    resources :probations do
      collection do
        post :pass
        post :fail
      end
    end
  end
  
  
  
  
  namespace :worker do
    resources :resumes do
      collection do
        post :ajax_save
        post :update_price
        post :recharge
      end
    end
    resources :resume_experiences do
      collection do
        post :ajax_save
      end
    end
    resources :resume_objects do
      collection do
        post :ajax_save
      end
    end
    resources :resume_educations do
      collection do
        post :ajax_save
      end
    end
    resources :radars do
      collection do
        post :save
      end
    end
    resources :applies do
    end
    resources :resume_radars
    resources :invites
    resources :auditions do
    end
  end
  
  
  namespace :accounts do
    resources :favorites do
      collection do
        post :ajax_create
        post :ajax_destroy
      end
    end
  end
  
  
  

  
end

app/controllers/accounts/companies_controller.rb
class Accounts::CompaniesController < ApplicationController
  before_action :authenticate_account!
  
  def new
    if current_account.company.present?
      flash[:error] = "已经完善过公司信息"
      cookies[:goto] ||= "/"
      redirect_to error_notice_index_index_path and return
    end
  end
  
  def create
    company = current_account.build_company(company_create_params)
    unless company.save
      flash[:error] = company.errors.messages.inject({}){|hash, item| hash[item[0]] = item[1]*','; hash}
      redirect_to :back and return
    end
    #保存所在公司
    current_account.save
    
    redirect_to cookies[:goto]||accounts_profile_index_path
  end
  
  private  
  def company_create_params  
    params.require(:company).permit()  
  end  
end

app/controllers/hr/applies_controller.rb
class Hr::AppliesController < ApplicationController
  before_action :authenticate_account!
  include DiversityResult
  
  def index
    @items = WorkflowApply.by_hr_account_id(current_account.id).order_ct_desc
    @items = @items.by_status([:status_apply_normal]) if params[:status] == "status_apply_normal"
    @items = @items.by_status([:status_apply_hr_receive]) if params[:status] == "status_apply_hr_receive"
    @items = @items.by_status([:status_apply_hr_reject]) if params[:status] == "status_apply_hr_reject"
    @items = @items.by_status([:status_wait_audition]) if params[:status] == "status_wait_audition"
    @items = @items.by_status([:status_audition_passed]) if params[:status] == "status_audition_passed"
    @items = @items.by_status([:status_audition_failed]) if params[:status] == "status_audition_failed"
    @items = @items.by_status([:status_probation_passed]) if params[:status] == "status_probation_passed"
    @items = @items.by_status([:status_probation_failed]) if params[:status] == "status_probation_failed"
  end
  
  def receive
    begin
      workflow = (WorkflowApply.find(params[:id]) rescue raise "申请不存在")
      workflow.set_status_to_apply_hr_receive! rescue raise "操作失败"
      flash[:success] = "操作成功"
    rescue Exception => ex
      flash[:error] = ex.message
      logger.error "action error log================================================"
      logger.error ex.message
      logger.error ex.backtrace
    end
    dr_render do
      redirect_to :back
    end
  end
  
  def accept
    begin
      workflow = (WorkflowApply.find(params[:id]) rescue raise "申请不存在")
      workflow.set_status_to_wait_audition! rescue raise "操作失败"
      flash[:success] = "操作成功"
    rescue Exception => ex
      flash[:error] = ex.message
      logger.error "action error log================================================"
      logger.error ex.message
      logger.error ex.backtrace
    end
    dr_render do
      redirect_to :back
    end
  end
  
  def reject
    begin
      workflow = (WorkflowApply.find(params[:id]) rescue raise "申请不存在")
      workflow.set_status_to_apply_hr_reject! rescue raise "操作失败"
      flash[:success] = "操作成功"
    rescue Exception => ex
      flash[:error] = ex.message
      logger.error "action error log================================================"
      logger.error ex.message
      logger.error ex.backtrace
    end
    dr_render do
      redirect_to :back
    end
  end
  
  
end

app/controllers/hr/auditions_controller.rb
class Hr::AuditionsController < ApplicationController
  before_action :authenticate_account!
  include DiversityResult
  
  def pass
    begin
      workflow = (Workflow.unscoped.find(params[:id]) rescue raise "面试不存在")
      workflow.set_status_to_audition_passed! rescue raise "操作失败"
      flash[:success] = "操作成功"
    rescue Exception => ex
      flash[:error] = ex.message
      logger.error "action error log================================================"
      logger.error ex.message
      logger.error ex.backtrace
    end
    dr_render do
      redirect_to :back
    end
  end
  
  def fail
    begin
      workflow = (Workflow.unscoped.find(params[:id]) rescue raise "面试不存在")
      workflow.set_status_to_audition_failed! rescue raise "操作失败"
      flash[:success] = "操作成功"
    rescue Exception => ex
      flash[:error] = ex.message
      logger.error "action error log================================================"
      logger.error ex.message
      logger.error ex.backtrace
    end
    dr_render do
      redirect_to :back
    end
  end
end

app/controllers/hr/companies_controller.rb
class Hr::CompaniesController < ApplicationController
  before_action :authenticate_account!
  
  def new
    redirect_to edit_account_registration_path if current_account.company.present?
  end
  
  def create
    company = current_account.build_company(company_create_params)
    unless company.save
      flash[:error] = company.errors.messages.inject({}){|hash, item| hash[item[0]] = item[1]*','; hash}
      redirect_to :back and return
    end
    #保存所在公司
    current_account.save
    
    redirect_to cookies[:goto]||edit_account_registration_path
  end
  
  def update
    company = current_account.company
    company.assign_attributes(company_create_params)
    unless company.save
      flash[:error] = company.errors.messages.inject({}){|hash, item| hash[item[0]] = item[1]*','; hash}
      redirect_to :back and return
    end
    
    redirect_to cookies[:goto]||edit_account_registration_path
  end
  
  def ajax_update_logo
    result = {status: "success"}
    begin
      company = current_account.company
      company.logo = params[:file]
      unless company.save
        raise AjaxException.new(company.errors.messages.inject({}){|hash, item| hash[item[0]] = item[1]*','; hash})
      end
      result[:content] = company.logo(:thumb)
    rescue Exception => ex
      result = {status: "error", content: ex.message}
      logger.error "ajax_update_logo error log================================================"
      logger.error ex.message
      logger.error ex.backtrace
    end
    render text: result.to_json
  end
  
  private  
  def company_create_params  
    params.require(:company).permit(:name, :home_page, :financing_stage_id, :area, :nature_id, :industry_id, :tel, :email, :content)
  end  
end

app/controllers/hr/company_members_controller.rb
class Hr::CompanyMembersController < ApplicationController
  before_action :authenticate_account!
  include DiversityResult
  
  def create
    begin
      object = CompanyMember.new(company_member_create_params)
      unless object.save
        raise AjaxException.new(object.errors.messages.inject({}){|hash, item| hash[item[0]] = item[1]*','; hash})
      end
      flash[:success] = "添加成功"
    rescue Exception => ex
      flash[:error] = ex.message
      logger.error "action error log================================================"
      logger.error ex.message
      logger.error ex.backtrace
    end
    dr_render do
      redirect_to :back
    end
  end
  
  private  
  def company_member_create_params  
    params.require(:company_member).permit(:company_id, :name, :post)  
  end 
end

app/controllers/hr/company_scenes_controller.rb
class Hr::CompanyScenesController < ApplicationController
  before_action :authenticate_account!
  include DiversityResult
  
  def create
    begin
      object = CompanyScene.new(company_scene_create_params)
      unless object.save
        raise AjaxException.new(object.errors.messages.inject({}){|hash, item| hash[item[0]] = item[1]*','; hash})
      end
      flash[:success] = "添加成功"
    rescue Exception => ex
      flash[:error] = ex.message
      logger.error "action error log================================================"
      logger.error ex.message
      logger.error ex.backtrace
    end
    dr_render do
      redirect_to :back
    end
  end
  
  private  
  def company_scene_create_params  
    params.require(:company_scene).permit(:company_id, :name)  
  end 
end

app/controllers/hr/index_controller.rb
class Hr::IndexController < ApplicationController
  before_action :authenticate_account!
  
  def index
    #判断用户是否为hr，不是则跳转到首页
    redirect_to index_index_path and return unless current_account.account_type == Account::ACCOUNT_TYPE_HR
    #已发布职位的标签列表
    tags = current_account.posts.tag_counts.map &:name
    @resumes = AccountResume.tagged_with(tags, :any => true).by_ct_desc.includes(:account).page(params[:page]).per(5)
    #读取搜索记录
    @search_logs = current_account.hr_search_logs.by_search_num_desc.by_ct_desc.limit(4)
  end
  
  def search
    tags = params[:tags].to_s
    area = params[:area].to_s
    year = params[:year]
    
    #记录搜索日志
    if tags.present?
      log = current_account.hr_search_logs.find_or_create_by(area: (area.blank? ? nil : area), post: tags, year: (year.to_i == 0 ? nil : year))
      log.search_num = log.search_num.to_i + 1
      log.save
    end
    #搜索
    @resumes = AccountResume.search(tags, area, year).page(params[:page]).per(5)
    
    
    #读取搜索记录
    @search_logs = current_account.hr_search_logs.by_search_num_desc.by_ct_desc.limit(4)
    render :index
  end
  
  def show
    @resume = AccountResume.find(params[:id])
    @account = @resume.account
    @experiences = @resume.account_resume_experiences.order_start_time_desc
  end
end

app/controllers/hr/posts_controller.rb
class Hr::PostsController < ApplicationController
  before_action :authenticate_account!
  include DiversityResult
  
  def index
    @posts = current_account.posts.ct_desc
    @posts = @posts.by_status([:status_normal]) if params[:status] == "status_normal"
    @posts = @posts.by_status([:status_off_shelves]) if params[:status] == "status_off_shelves"
    @posts = @posts.page(params[:id]).per(8)
  end
  
	def new
    flash.clear
    if current_account.company.blank?
      cookies[:goto] = request.original_url
      redirect_to new_hr_company_path and return
    end
    
		@post = Post.new(email: current_account.email)
    @new_posts_for_today = current_account.posts.by_date(Date.today).size
	end
  
  def create
    post = Post.new(post_create_params)
    post.account_id = current_account.id
    post.content = params[:editorValue]
    post.tag_list.add params[:addhopecontenthidden].split(",")
    post.sanitize_content = Nokogiri::HTML(post.content).text if post.content.present? #去掉html标记的内容取200个字
    #TODO: 公司ID
    post.company_id = Company.last.id
    post.save
    flash[:notice] = "保存完成"
    redirect_to hr_post_path(post)
  end
  
  def show
    @post = Post.find(params[:id])
    @company = @post.company
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def destroy
    begin
      post = Post.find(params[:id])
      post.soft_delete!
      flash[:success] = "操作成功"
    rescue Exception => ex
      flash[:error] = ex.message
      logger.error "action error log================================================"
      logger.error ex.message
      logger.error ex.backtrace
    end
    dr_render do
      redirect_to :back
    end
  end
  
  #def ajax_get_tags
  #  Elasticsearch::Client.new.indices.analyze(index: "index", text: params[:title])
  #end
  
  #修改职位上架下架状态
  def set_status
    begin
      post = Post.find(params[:id])
      if post.status_off_shelves?
        post.set_status_to_normal!
      else
        post.set_status_to_off_shelves!
      end
    rescue Exception => ex
      flash[:error] = ex.message
      logger.error "action error log================================================"
      logger.error ex.message
      logger.error ex.backtrace
    end
    dr_render do
      redirect_to :back
    end
  end
  
  private  
  def post_create_params  
    params.require(:post).permit(:title, :area, :price_min, :price_max, :address, :email, :department, :content)  
  end  
end

app/controllers/hr/probations_controller.rb
class Hr::ProbationsController < ApplicationController
  before_action :authenticate_account!
  include DiversityResult
  
  def pass
    begin
      workflow = (Workflow.unscoped.find(params[:id]) rescue raise "试用不存在")
      workflow.set_status_to_probation_passed! rescue raise "操作失败"
      flash[:success] = "操作成功"
    rescue Exception => ex
      flash[:error] = ex.message
      logger.error "action error log================================================"
      logger.error ex.message
      logger.error ex.backtrace
    end
    dr_render do
      redirect_to :back
    end
  end
  
  def fail
    begin
      workflow = (Workflow.unscoped.find(params[:id]) rescue raise "试用不存在")
      workflow.set_status_to_probation_failed! rescue raise "操作失败"
      flash[:success] = "操作成功"
    rescue Exception => ex
      flash[:error] = ex.message
      logger.error "action error log================================================"
      logger.error ex.message
      logger.error ex.backtrace
    end
    dr_render do
      redirect_to :back
    end
  end
end

app/controllers/hr_controller.rb
class HrController < ApplicationController
  before_action :authenticate_account!
  
  def index
    #判断用户是否为hr，不是则跳转到首页
    redirect_to index_index_path and return unless current_account.account_type == Account::ACCOUNT_TYPE_HR
    #已发布职位的标签列表
    tags = current_account.posts.tag_counts.map &:name
    @resumes = AccountResume.tagged_with(tags, :any => true).by_ct_desc.includes(:account).page(params[:page]).per(5)
    #读取搜索记录
    @search_logs = current_account.hr_search_logs.by_search_num_desc.by_ct_desc.limit(4)
  end
  
  def search
    tags = params[:tags].to_s
    area = params[:area].to_s
    year = params[:year]
    
    #记录搜索日志
    if tags.present?
      log = current_account.hr_search_logs.find_or_create_by(area: (area.blank? ? nil : area), post: tags, year: (year.to_i == 0 ? nil : year))
      log.search_num = log.search_num.to_i + 1
      log.save
    end
    #搜索
    @resumes = AccountResume.search(tags, area, year).page(params[:page]).per(5)
    
    
    #读取搜索记录
    @search_logs = current_account.hr_search_logs.by_search_num_desc.by_ct_desc.limit(4)
    render :index
  end
  
  def show
    @resume = AccountResume.find(params[:id])
    @account = @resume.account
    @experiences = @resume.account_resume_experiences.order_start_time_desc
  end
end

app/helpers/accounts/companies_helper.rb
module Accounts::CompaniesHelper
end

app/helpers/hr/applies_helper.rb
module Hr::AppliesHelper
end

app/helpers/hr/auditions_helper.rb
module Hr::AuditionsHelper
end

app/helpers/hr/company_members_helper.rb
module Hr::CompanyMembersHelper
end

app/helpers/hr/company_scenes_helper.rb
module Hr::CompanyScenesHelper
end

app/helpers/hr/probations_helper.rb
module Hr::ProbationsHelper
end

app/helpers/hr_helper.rb
module HrHelper
  def hr_apply_normal_count
    count = Workflow.by_status(:status_apply_normal).by_hr_account_id(current_account.id).count
    return "" if count.zero?
    raw <<-HTML
    <span>#{count}</span>
    HTML
  end
end

app/views/hr/companies/_detial.html.erb
<h2 class="h2Title">团队核心成员</h2>
<%company = current_account.company || current_account.build_company%>
<%= form_for company.company_members.build, url: hr_company_members_path, :html => { :multipart => true } do |f|%>
<%= f.hidden_field :company_id%>
<div class="form">
	<div class="frm">
		<span class="">成员头像</span>
		<div class="file">
			<span class="fImg"><img src="../images/file_default.png" alt="" /></span>
			<a href="#">上传照片</a>
		</div>
		<!-- <span class="error">*请填写职位名称</span> -->
	</div>
	<div class="frm">
		<span class="">成员姓名</span>
		<%= f.text_field :name%>
		<span class="error">*请填写昵称</span>
	</div>
	<div class="frm">
		<span class="">成员职位</span>
		<%= f.text_field :post%>
		<span class="error">*请填写职位</span>
	</div>
</div>
<div class="jobBtns">
  <%= f.submit "添加成员"%>
	<a href="#" class="btn">添加成员</a>
</div>
<%end%>
<ul class="Imgslist userImgsList">
  <% company.company_members.each do |member|%>
	<li>
		<div class="userImg">
			<span class="uImg"><img src="../images/placeDemo.jpg" alt="" /></span>
		</div>
		<p><%= member.name%></p>
		<p><%= member.post%></p>
	</li>
  <%end%>
</ul>
<h2 class="h2Title">公司场景展示</h2>
<%company = current_account.company || current_account.build_company%>
<%= form_for company.company_scenes.build, url: hr_company_scenes_path, :html => { :multipart => true } do |f|%>
<%= f.hidden_field :company_id%>
<div class="form">
	<div class="frm">
		<span class="">公司图片</span>
		<div class="file">
			<span class="fImg"><img src="../images/file_default.png" alt="" /></span>
			<a href="#">上传照片</a>
		</div>
		<!-- <span class="error">*请填写职位名称</span> -->
	</div>
	<div class="frm">
		<span class="">场景名称</span>
		<%= f.text_field :name%>
		<span class="error">*请填写昵称</span>
	</div>
</div>
<div class="jobBtns">
	<%= f.submit "添加照片"%>
	<a href="#" class="btn">添加照片</a>
</div>
<%end%>
<ul class="Imgslist placeImgslist">
  <% company.company_scenes.each do |scene|%>
	<li>
		<div class="placeImg">
			<span class="pImg"><img src="../images/placeDemo.jpg" alt="" /></span>
			<a href="#">修改</a>
		</div>
		<p><%= scene.name%></p>
	</li>
  <%end%>
</ul>
<div class="form">
	<div class="frm">
		<span class="">公司介绍</span>
		<textarea name="" id=""></textarea>
		<span class="error">*请填写昵称</span>
	</div>
</div>
<div class="jobBtns">
	<!-- <a href="#" class="btnR">发起面试</a><a href="#" class="btnR">收    藏</a> -->
	<a href="#" class="btn">保&nbsp;存</a>
</div>

app/views/hr/companies/_form.html.erb
<%company = current_account.company || current_account.build_company%>
<%= form_for company, url: company.new_record? ? hr_companies_path : hr_company_path(company) do |f|%>
<h2 class="h2Title">公司信息</h2>
<div class="form">
	<div class="frm">
		<span class="">公司全称</span>
		<%= f.text_field :name,id: "mycompany",class: "verification","data-type" => "notnull","data-nohide" => "1", "error-id" => "errormycompany"%>
		<span class="error" id="errormycompany">*请填写公司名称</span>
	</div>
	<div class="frm">
		<span class="">联系电话</span>
		<%= f.text_field :tel,id: "mytel",class: "verification","data-type" => "tel","data-nohide" => "1", "error-id" => "errormytel"%>
		<span class="error" id="errormytel">*请填写“区号-号码”或手机号</span>
	</div>
	<div class="frm">
		<span class="">接受简历的邮箱</span>
		<%= f.text_field :email,id: "myemail",class: "verification","data-type" => "email","data-nohide" => "1", "error-id" => "errormyemail"%>
		<span class="error" id="errormyemail">*请填写接受简历的邮箱</span>
	</div>
	<div class="frm">
		<span class="">公司性质</span>
		<%= f.select :nature_id, Nature.all.map{|item| [item.name, item.id]}, id: "nature_id", class: "verification", "data-type" => "nature_id", "data-nohide" => "1", "error-id" => "errnature"%>
		<span class="error" id="errnature">*请填写公司性质</span>
	</div>
	<div class="frm">
		<span class="">公司行业</span>
		<%= f.select :industry_id, Industry.all.map{|item| [item.name, item.id]}, id: "industry_id", class: "verification", "data-type" => "industry_id", "data-nohide" => "1", "error-id" => "errorindustry_id"%>
		<span class="error" id="errorindustry_id">*请填写公司行业</span>
	</div>
	<div class="frm">
		<span class="">网 址</span>
		<%= f.text_field :home_page, id: "home_page", class: "verification", "data-type" => "home_page", "data-nohide" => "1", "error-id" => "errorhome_page"%>
		<span class="error" id="errorhome_page">*请填写网址</span>
	</div>
	<div class="frm">
		<span class="">融资阶段</span>
		<%= f.select :financing_stage_id, FinancingStage.all.map{|item| [item.name, item.id]}, id: "financing_stage", class: "verification", "data-type" => "financing_stage", "data-nohide" => "1", "error-id" => "errorfinancing_stage"%>
		<span class="error" id="errorfinancing_stage">*请填写融资阶段</span>
	</div>
	<div class="frm">
		<span class="">公司地址</span>
		<%= f.text_field :area, id: "area", class: "verification", "data-type" => "area", "data-nohide" => "1", "error-id" => "errorarea"%>
		<span class="error" id="errorarea">*请填写公司地址</span>
	</div>
  <div class="frm">
		<span class="">公司介绍</span>
    <%= f.text_area :content%>
		<span class="error">*请填写公司介绍</span>
  </div>
</div>
<div class="registerBtn">
  <%= f.submit raw("保&nbsp;存"), class: "btn"%>
</div>
<%end%>

app/views/hr/companies/edit.html.erb
<div class="mainContainer step2">
	<div class="main">
    <%= render partial: "/hr/companies/form"%>
    <br />
    <%#= render partial: "/hr/companies/detial"%>   
  </div>
</div>

app/views/hr/companies/new.html.erb
<div class="mainContainer step2">
	<div class="main">
		<!-- <div class="mm"> -->
			<h2 class="h2Title">招聘方注册第2步</h2>
			<%= form_for Company.new, url: hr_companies_path do |f|%>
			  <%= render partial: "/hr/companies/form", locals: {f: f}%>
      <%end%>
			<div class="questions">
				<dl>
					<dt>常见问题：</dt>
					<dd class="highlight">问：填写个人邮箱可以么？</dd>
					<dd>答：不可以。为了保证每个职位的真实性，鸟窝严格要求招聘方必须提供公司邮箱。（公司邮箱是指以你的公司网址为后缀的免费公司邮箱，例如鸟窝的公司邮箱后缀是@niaowo.com）即使是初创公司也必须提供公司邮箱才允许开通招聘。</dd>
					<dd  class="highlight">问：公司没有公司邮箱怎么办？</dd>
					<dd>答：鸟窝推荐使用免费、稳定的腾讯企业邮箱（网址：http://exmail.qq.com），根据邮箱申请指南进行操作，很快就可以拥有以你的公司网址为后缀的免费公司邮箱。</dd>
				</dl>
				<dl>
					<dt>公司全称</dt>
					<dd  class="highlight">请输入与公司营业执照一致的公司全称，审核通过后不可更改</dd>
				</dl>
				<dl>
					<dt>没有收到确认邮件，怎么办？</dt>
					<dd  class="highlight">1.邮箱地址填写错误？ 重新填写邮箱地址</dd>
					<dd  class="highlight">2.看看是否在邮箱的垃圾邮件、广告邮件目录里</dd>
					<dd  class="highlight">3.稍等几分钟，若还未收到验证邮件， 重新发送验证邮件</dd>
					<dd  class="highlight">4.还未收到验证邮件，请联系我们，邮箱：939898101@qq.com</dd>
				</dl>
				<p> 如有其它问题，请发送问题到<span class="highlight">939898101@qq.com </span>我们会尽快为你解决。</p>
			</div>
		</div>
	<!-- </div> -->
	
</div>